### ISSUE TITLE
MongoClient와 mongoose를 동시에 사용할 경우 라이브러리 혼용 주의

### ISSUE THREAD

**Issue by ucharles** [ucharles/gachatory#38]
## 에러 내용
- `next-auth` 도입을 위해 `@auth/mongodb-adapter` 라이브러리를 설치
- `mongodb.ts`를 작성
- 기존 코드에 문자열 `id`를 `ObjectId`로 변환하기 위해 `mongodb`의 `new ObjectId("id")`를 사용 중이었음
- `ObjectId`를 이용하여 검색하는 **API**에서 아래 에러 발생

## 상세 에러 내용
```
DB ConnectedMongoose: capsule-toy.findOne({ _id: ObjectId("64fc8898d2620253dcf8eaad") }, {})
BSONVersionError: Unsupported BSON version, bson types must be from bson 5.0 or later
    at serializeInto (E:\Git\gachatory\next-app\node_modules\bson\lib\bson.cjs:3670:23)
    at serializeObject (E:\Git\gachatory\next-app\node_modules\bson\lib\bson.cjs:3232:22)
    at serializeInto (E:\Git\gachatory\next-app\node_modules\bson\lib\bson.cjs:3666:25)
    at Object.serialize (E:\Git\gachatory\next-app\node_modules\bson\lib\bson.cjs:4048:32)
    at Msg.serializeBson (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\commands.js:383:21)
    at Msg.makeDocumentSegment (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\commands.js:377:37)
    at Msg.toBin (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\commands.js:366:29)
    at MessageStream.writeCommand (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:43:34)
    at write (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:479:30)
    at Connection.command (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:312:13)
    at E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\sdam\server.js:209:18
    at Object.callback (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection_pool.js:321:13)
    at ConnectionPool.processWaitQueue (E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection_pool.js:543:33)
    at E:\Git\gachatory\next-app\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection_pool.js:204:37
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

## 해결법
- 기존 `mongoose`를 사용하는 코드의 `ObjectId` 변환은 `mongoose.Type.ObjectId`를 사용
- 변환 전
``` javascript
import { ObjectId } from "mongodb"

const string = "64fc8898d2620253dcf8eaad"
const objectid = new ObjectId(string)
```
- 변환 후
``` javascript
import mongoose from "mongoose"

const string = "64fc8898d2620253dcf8eaad"
const objectid = new mongoose.Types.ObjectId(string)
```
## 관련 이슈
- #28

**Comment by ucharles** [comment]
https://github.com/ucharles/gachatory/pull/94 에서 반영 완료
