### ISSUE TITLE
`/[lng]`의 무한 스크롤 Hydration Error

### ISSUE THREAD

**Issue by ucharles** [ucharles/gachatory#58]
## 현상
- `intersectionObserver`가 화면에 표시되어도 추가 데이터가 fetch 되지 않음?
- 페이지의 아무 곳이나 클릭하면 fetch가 일어남 (???)
- 개발 환경, 개발 빌드 환경에서는 해당 현상이 발생하지 않음
- 프로덕션 환경에서만 발생

## 구동 환경
- iPhone SE 2 Safari: 정상 작동
- iPhone SE 2 Chrome: 정상 작동 (???)

## 에러
프로덕션 환경에서만 아래 에러 발생
```
Uncaught Error: Minified React error #329; visit https://reactjs.org/docs/error-decoder.html?invariant=329 
for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ib (fd9d1056-b4d4cc61ccc30446.js:9:87191)
    at MessagePort.M (864-bc5336431ec13e15.js:25:1665)
ib	@	fd9d1056-b4d4cc61ccc30446.js:9
M	@	864-bc5336431ec13e15.js:25
```
- https://legacy.reactjs.org/docs/error-decoder.html/?invariant=329
- https://legacy.reactjs.org/docs/error-decoder.html/?invariant=418
- https://legacy.reactjs.org/docs/error-decoder.html/?invariant=423

**Comment by ucharles** [comment]
- #61 에서 hydration은 해결되었지만 뒤로가기 시 내용 보존이 안됨
